version: '3.8'

services:

  db:
    image: postgres:13-alpine
    volumes:
      #- postgres_data:/var/lib/postgresql/data/
      - postgres_data_prod:/var/lib/postgresql/data/
    #environment:
      #- POSTGRES_USER=hello_flask
      #- POSTGRES_PASSWORD=hello_flask
      #- POSTGRES_DB=hello_flask_dev
    env_file:
      - ./.env.db.prod

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 api:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  postgres_data_prod: