version: '3.8'

services:

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 api:app
    volumes:
      - static_volume:/home/app/api/project/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/api/project/static
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data_prod:
  static_volume: